### ISSUE TITLE
TravisCI yaml file

### ISSUE THREAD

**Issue by amirrajan** [amirrajan/rubymotion-applied#126]
Sample yaml file to do RubyMotion builds from Travis:

```yaml
language: objective-c
os: osx
osx_image: xcode10.2
env:
  - TMP_DIR=./tmp  # For motion repo, so it doesn't attempt to use /tmp, to which it has no access
before_install:
  - wget http://travisci.rubymotion.com/ -O RubyMotion-TravisCI.pkg
  - sudo installer -pkg RubyMotion-TravisCI.pkg -target /
  - cp -r /usr/lib/swift/*.dylib /Applications/Xcode.app/Contents/Frameworks/
  - touch /Applications/Xcode.app/Contents/Frameworks/.swift-5-staged
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion
  - eval "sudo motion activate $RUBYMOTION_LICENSE"
  - sudo motion update && motion repo
gemfile:
  - Gemfile
script: bundle exec rake spec
```

You'll need to set an environment variable with your license key to activate RM in this case `$RUBYMOTION_LICENSE`.

**Comment by andrewhavens** [comment]
This Travis config has been tested and works with RubyMotion 6.5, Xcode 11.2, and iOS 13. It uses an official starter license key for use with open source projects.

```yaml
os: osx
osx_image: xcode11.2
env:
  global:
    - RUBYMOTION_LICENSE=1dcac45cc434293009f74b33037bdf7361a3a1ff # Official license key for open-source projects
    - TMP_DIR=./tmp  # For motion repo, so it doesn't attempt to use /tmp, to which it has no access
before_install:
  - wget http://travisci.rubymotion.com/ -O RubyMotion-TravisCI.pkg
  - sudo installer -pkg RubyMotion-TravisCI.pkg -target /
  - cp -r /usr/lib/swift/*.dylib /Applications/Xcode.app/Contents/Frameworks/
  - touch /Applications/Xcode.app/Contents/Frameworks/.swift-5-staged
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion
  - eval "sudo motion activate $RUBYMOTION_LICENSE"
  - sudo motion update
  - motion repo
script:
  - bundle exec rake spec
```

(Updated on 11/7/19 to work with RM 6.5)
